COUPLER_OUTER_RADIUS = 3.5;
COUPLER_WALL_WIDTH = 1;
COUPLER_TOP_WIDTH = 1;
COUPLER_HEIGHT = 4;

$fn=20;

difference() {
    cylinder(r=COUPLER_OUTER_RADIUS, h=COUPLER_HEIGHT);
    cylinder(r=COUPLER_OUTER_RADIUS-COUPLER_WALL_WIDTH, h=COUPLER_HEIGHT-COUPLER_TOP_WIDTH);
}
